<a href="https://colab.research.google.com/github/bala-baskar/aiml_tech_courses/blob/main/pytorch/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim, scalar.item()

(0, 7)

In [ ]:
# vector
vector = torch.tensor([10,4])
vector

tensor([10,  4])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix

MATRIX = torch.tensor([[10,2],[4,6]])
MATRIX

tensor([[10,  2],
        [ 4,  6]])

In [ ]:
MATRIX.shape, MATRIX.ndim

(torch.Size([2, 2]), 2)

In [ ]:
MATRIX[0][1]

tensor(2)

In [ ]:
# Tensor

tensor = torch.tensor([[[1,2,3],
                       [3,4,5],
                       [4,5,6]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [ ]:
tensor.ndim, tensor.shape

(3, torch.Size([1, 3, 3]))

In [ ]:
tensor[0][1][2] = 10

In [ ]:
tensor

tensor([[[ 1,  2,  3],
         [ 3,  4, 10],
         [ 4,  5,  6]]])

In [ ]:
# Create 4 dimensional tensor

tensor_4 = torch.tensor([[[[1,2,3],[2,3,4]]]])
print(tensor_4.ndim, tensor_4.shape)

4 torch.Size([1, 1, 2, 3])


## Random Tensors

In [ ]:
random_tensor = torch.rand(3,4,4)
random_tensor

tensor([[[0.5152, 0.7787, 0.0871, 0.8001],
         [0.5789, 0.5259, 0.9271, 0.4165],
         [0.6558, 0.4168, 0.9528, 0.4487],
         [0.5135, 0.3161, 0.4612, 0.1427]],

        [[0.8005, 0.2428, 0.9780, 0.5108],
         [0.5347, 0.5453, 0.2820, 0.0273],
         [0.4749, 0.5715, 0.9218, 0.2357],
         [0.1780, 0.8987, 0.1814, 0.0804]],

        [[0.2944, 0.0967, 0.0686, 0.7712],
         [0.7265, 0.9684, 0.0779, 0.2411],
         [0.7911, 0.2088, 0.1703, 0.7394],
         [0.6599, 0.9235, 0.7430, 0.9580]]])

In [ ]:
random_tensor.ndim, random_tensor.shape

(3, torch.Size([3, 4, 4]))

## Zeros and ones

In [ ]:
zeros = torch.zeros(size=(3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zeros + ones * 5

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [ ]:
ones.dtype

torch.float32

## Create range and tensor like

In [ ]:
range_tensors = torch.arange(1,10)
range_tensors

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range_1_100_5 = torch.arange(1,100,5)
range_1_100_5

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [ ]:
# creating tensors like
tensor_like = torch.zeros_like(input=range_tensors)
#tensor_like = torch.ones_like(input=range_tensors)
tensor_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor data type

In [ ]:
tensor_1 = torch.tensor([2.0,3.0,1.0],
                        dtype=torch.float16,
                        device="cpu",
                        requires_grad=False)
tensor_1

tensor([2., 3., 1.], dtype=torch.float16)

In [ ]:
tensor_1.type(torch.float32).dtype

torch.float32

In [ ]:
tensor_1.dtype, tensor_1.shape, tensor_1.device

(torch.float16, torch.Size([3]), device(type='cpu'))

## Manipulating tensors

In [ ]:
tensor_1 = torch.rand(3,4)
tensor_2 = torch.rand(3,4)
tensor_1, tensor_2

(tensor([[0.9336, 0.1272, 0.5977, 0.9558],
         [0.0528, 0.0547, 0.6844, 0.6346],
         [0.0774, 0.9631, 0.3322, 0.6970]]),
 tensor([[0.3271, 0.1307, 0.3003, 0.2674],
         [0.9873, 0.9378, 0.5347, 0.5788],
         [0.1532, 0.7754, 0.0302, 0.2143]]))

In [ ]:
tensor_1 + tensor_2

tensor([[1.2607, 0.2579, 0.8980, 1.2232],
        [1.0401, 0.9925, 1.2192, 1.2134],
        [0.2306, 1.7385, 0.3624, 0.9113]])

In [ ]:
tensor_1 - tensor_2

tensor([[ 0.6064, -0.0036,  0.2974,  0.6884],
        [-0.9345, -0.8831,  0.1497,  0.0558],
        [-0.0758,  0.1878,  0.3021,  0.4827]])

In [ ]:
tensor_1 * tensor_2

tensor([[0.3054, 0.0166, 0.1795, 0.2556],
        [0.0522, 0.0513, 0.3660, 0.3673],
        [0.0119, 0.7468, 0.0100, 0.1494]])

In [ ]:
tensor_1 / tensor_2

tensor([[ 2.8538,  0.9727,  1.9905,  3.5742],
        [ 0.0535,  0.0583,  1.2799,  1.0965],
        [ 0.5053,  1.2422, 11.0176,  3.2522]])

In [ ]:
torch.add(tensor_1, 10)

tensor([[10.9336, 10.1272, 10.5977, 10.9558],
        [10.0528, 10.0547, 10.6844, 10.6346],
        [10.0774, 10.9631, 10.3322, 10.6970]])

In [ ]:
torch.subtract(tensor_2, 5)

tensor([[-4.6729, -4.8693, -4.6997, -4.7326],
        [-4.0127, -4.0622, -4.4653, -4.4212],
        [-4.8468, -4.2246, -4.9698, -4.7857]])

In [ ]:
torch.mul(tensor_1, 2)

tensor([[1.8672, 0.2543, 1.1954, 1.9116],
        [0.1056, 0.1094, 1.3689, 1.2692],
        [0.1548, 1.9263, 0.6645, 1.3940]])

In [ ]:
tensor_1.mul(2)

tensor([[1.8672, 0.2543, 1.1954, 1.9116],
        [0.1056, 0.1094, 1.3689, 1.2692],
        [0.1548, 1.9263, 0.6645, 1.3940]])

In [ ]:
torch.matmul(tensor_1.T,tensor_2)

tensor([[0.3694, 0.2316, 0.3109, 0.2968],
        [0.2432, 0.8147, 0.0965, 0.2721],
        [0.9222, 0.9776, 0.5555, 0.6272],
        [1.0460, 1.2605, 0.6474, 0.7722]])

In [ ]:
tensor_1.T.matmul(tensor_2)

tensor([[0.3694, 0.2316, 0.3109, 0.2968],
        [0.2432, 0.8147, 0.0965, 0.2721],
        [0.9222, 0.9776, 0.5555, 0.6272],
        [1.0460, 1.2605, 0.6474, 0.7722]])

In [ ]:
torch.sum(tensor_1.T.matmul(tensor_2))

tensor(9.4439)

In [ ]:
tensor_1 = torch.rand(3,3)
tensor_1

tensor([[0.8188, 0.8531, 0.7147],
        [0.4068, 0.2145, 0.6191],
        [0.6316, 0.7110, 0.0488]])

In [ ]:
tensor_1.min(), tensor_1.max()

(tensor(0.0488), tensor(0.8531))

In [ ]:
tensor_1.argmin(), tensor_1.argmax()

(tensor(8), tensor(1))

## Reshaping, viewing, squeeze & unsqueeze

In [ ]:
tensor_1 = torch.arange(1,10)
tensor_1

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor_3_3 = tensor_1.reshape(3,3)
tensor_3_3, tensor_3_3.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
z = tensor_3_3.view(1,9)
tensor_3_3, z

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [ ]:
torch.stack([z,z,z],dim=0).shape

torch.Size([3, 1, 9])

In [ ]:
torch.stack([z,z,z],dim=1).shape

torch.Size([1, 3, 9])

In [ ]:
torch.hstack([z,z,z]).shape

torch.Size([1, 27])

In [ ]:
torch.vstack([z,z,z]).shape

torch.Size([3, 9])

In [ ]:
x = torch.rand(1,9).reshape(1,9)
x

tensor([[0.1651, 0.7044, 0.5131, 0.3334, 0.7076, 0.4914, 0.0373, 0.8505, 0.1545]])

In [ ]:
x.squeeze()

tensor([0.1651, 0.7044, 0.5131, 0.3334, 0.7076, 0.4914, 0.0373, 0.8505, 0.1545])

In [ ]:
x.squeeze().shape

torch.Size([9])

In [ ]:
x.unsqueeze(dim=2).shape

torch.Size([1, 9, 1])

1. squeeze - removes all single dimension from tensor
2. unsqueeze - adds single dimension in the given location
3. reshape - reshapes the tensor with the given shape
4. view - returns a view same as reshape
5. hstack - horizontally stack the tensors
6. vstack - vertically stack the tensors
7. permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
#image tensor
img = torch.rand(size=(224,224,3))
img

tensor([[[0.8533, 0.6861, 0.8365],
         [0.5966, 0.3686, 0.8920],
         [0.4590, 0.3086, 0.0179],
         ...,
         [0.8264, 0.3144, 0.4345],
         [0.8404, 0.1851, 0.2859],
         [0.9031, 0.1780, 0.0488]],

        [[0.2191, 0.2494, 0.9397],
         [0.1420, 0.2989, 0.9581],
         [0.4438, 0.5775, 0.1166],
         ...,
         [0.9499, 0.2400, 0.3770],
         [0.2507, 0.9825, 0.1435],
         [0.0035, 0.0547, 0.0361]],

        [[0.4767, 0.8956, 0.8948],
         [0.6250, 0.5306, 0.4800],
         [0.6214, 0.8692, 0.0525],
         ...,
         [0.8944, 0.8752, 0.5439],
         [0.9122, 0.7628, 0.1030],
         [0.7901, 0.1777, 0.2620]],

        ...,

        [[0.9044, 0.9037, 0.9183],
         [0.9409, 0.6653, 0.0298],
         [0.9871, 0.2303, 0.3166],
         ...,
         [0.5531, 0.6779, 0.7437],
         [0.5088, 0.8547, 0.5010],
         [0.7896, 0.9885, 0.8451]],

        [[0.0063, 0.7643, 0.8847],
         [0.3031, 0.1334, 0.7582],
         [0.

In [ ]:
# change the order of dimension
img.permute(2,1,0).shape, img.shape

(torch.Size([3, 224, 224]), torch.Size([224, 224, 3]))

In [ ]:
img[0,0,0] = 100
img

tensor([[[1.0000e+02, 6.8611e-01, 8.3650e-01],
         [5.9659e-01, 3.6857e-01, 8.9200e-01],
         [4.5896e-01, 3.0861e-01, 1.7902e-02],
         ...,
         [8.2636e-01, 3.1439e-01, 4.3454e-01],
         [8.4039e-01, 1.8506e-01, 2.8590e-01],
         [9.0312e-01, 1.7800e-01, 4.8836e-02]],

        [[2.1913e-01, 2.4942e-01, 9.3967e-01],
         [1.4203e-01, 2.9887e-01, 9.5810e-01],
         [4.4377e-01, 5.7746e-01, 1.1664e-01],
         ...,
         [9.4985e-01, 2.4001e-01, 3.7701e-01],
         [2.5074e-01, 9.8247e-01, 1.4350e-01],
         [3.4682e-03, 5.4715e-02, 3.6139e-02]],

        [[4.7670e-01, 8.9556e-01, 8.9477e-01],
         [6.2498e-01, 5.3063e-01, 4.7999e-01],
         [6.2140e-01, 8.6919e-01, 5.2500e-02],
         ...,
         [8.9438e-01, 8.7515e-01, 5.4391e-01],
         [9.1224e-01, 7.6282e-01, 1.0301e-01],
         [7.9012e-01, 1.7767e-01, 2.6200e-01]],

        ...,

        [[9.0442e-01, 9.0365e-01, 9.1829e-01],
         [9.4088e-01, 6.6527e-01, 2.9767e-02]

## Indexing

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0], x[0,0], x[:,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]), tensor([[1, 2, 3]]))

In [ ]:
x[0,0,0], x[0][0][0]

(tensor(1), tensor(1))

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:,1:,:], x[:,:,1]

(tensor([[[4, 5, 6],
          [7, 8, 9]]]),
 tensor([[2, 5, 8]]))

## Pytorch tensors & Numpy

In [ ]:
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
tensor.type(torch.float32).dtype

torch.float32

In [ ]:
tensor = torch.ones(10)
numpy_tensor = tensor.numpy()
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

## Random seed for reproducibility

In [ ]:
tensor_A = torch.rand(2,3)
tensor_B = torch.rand(2,3)
tensor_A, tensor_B, tensor_A == tensor_B

(tensor([[0.8602, 0.9759, 0.3528],
         [0.0777, 0.8974, 0.6294]]),
 tensor([[0.2333, 0.4380, 0.7737],
         [0.1635, 0.3575, 0.1572]]),
 tensor([[False, False, False],
         [False, False, False]]))

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(2,3)


torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(2,3)
tensor_A, tensor_B, tensor_A == tensor_B

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[True, True, True],
         [True, True, True]]))

## Access GPU using PyTorch

In [ ]:
torch.cuda.is_available()

False

In [ ]:
#Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
torch.cuda.device_count()

/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


0

In [ ]:
# Move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
tensor_on_gpu.device

device(type='cpu')

In [ ]:
# If tensor is on GPU, cant transform it to Numpy

tensor_on_gpu.cpu().numpy()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)